MVC_Kutuphane_2024-12/Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Devrekani_Sehitler_Kutuphanesi.Models.Entity;
namespace Devrekani_Sehitler_Kutuphanesi.Controllers
{
    public class DuyuruController : Controller
    {
        KutuphaneContext db = new KutuphaneContext();
        public ActionResult Index()
        {
            var degerler = db.TBL_DUYURULAR.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniDuyuru()
        {
           
            return View();
        }
        [HttpPost]
        public ActionResult YeniDuyuru(TBL_DUYURULAR t)
        {
            db.TBL_DUYURULAR.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruSil(int id)
        {
            var duyurusil = db.TBL_DUYURULAR.Find(id);
            db.TBL_DUYURULAR.Remove(duyurusil);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruDetay(TBL_DUYURULAR p)
        {
            var duyuru = db.TBL_DUYURULAR.Find(p.ID);
           
            return View("DuyuruDetay", duyuru);
        }
        public ActionResult DuyuruGuncelle(TBL_DUYURULAR t)
        {
            var duyuru = db.TBL_DUYURULAR.Find(t.ID);
            duyuru.KATEGORI = t.KATEGORI;
            duyuru.ICERIK = t.ICERIK;
            duyuru.TARIH = t.TARIH;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC_Kutuphane_2024-12/Views/Duyuru/DuyuruDetay.cshtml
@model Devrekani_Sehitler_Kutuphanesi.Models.Entity.TBL_DUYURULAR

@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Duyuru Detayı</h2>


@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">

        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control", @readonly = "true" })
        <br />
        <label>Duyuru Kategorisi</label>
        @Html.TextBoxFor(k => k.KATEGORI, new { @class = "form-control", @maxlength = "50" })
        <br />
        <label>Duyuru İçeriği</label>
        @Html.TextBoxFor(k => k.ICERIK, new { @class = "form-control", @maxlength = "50" })
        <br />
        <label>Duyuru Tarihi</label>
        @Html.TextBoxFor(k => k.TARIH, new { @class = "form-control", @maxlength = "50" })
        <br />
     
    </div>
    <div>
        <button class="btn btn-warning">Duyuru Güncelle</button>

    </div>
}

MVC_Kutuphane_2024-12/Views/Duyuru/Index.cshtml
@using Devrekani_Sehitler_Kutuphanesi.Models.Entity;
@model List<TBL_DUYURULAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
    string renk = "";
}

<h2>Duyurular</h2>
<table class="table table-bordered">
    <tr style="background-color:rgb(252,178,22)">
        <th>Duyuru No</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>

        <th>Detaylar</th>
    </tr>
    @foreach (var dyr in Model)
    {
        if (dyr.KATEGORI == "İletişim")
        {
            renk = "bg-warning text-black";
        }
        if (dyr.KATEGORI == "Kitapları Geciktirmeyin")
        {
            renk = "bg-danger text-white";
        }
        if (dyr.KATEGORI == "Yeni Kitap")
        {
            renk = "bg-success text-white";
        }
        if (dyr.KATEGORI == "Diğer")
        {
            renk = "bg-info text-white";
        }
       
        <tr class="@renk">
            <td>@dyr.ID</td>
            <td>@dyr.KATEGORI</td>
            <td>@Convert.ToDateTime(dyr.TARIH).ToString("dd/MM/yyyy")</td>
            <td>@Html.ActionLink("Sil", "DuyuruSil", new { id = dyr.ID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İstiyor Musunuz ?')" }) </td>
            @*<td><a href="/Category/KategoriSil/@ktg.ID" class="btn btn-danger">Sil</a></td>  ESKİ USÜL hrefle yapma  *@

            <td><a href="/Duyuru/DuyuruDetay/@dyr.ID" class="btn btn-success" style="background-color:brown">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Duyuru/YeniDuyuru" class="btn btn-primary">Yeni Duyuru Ekle</a>

MVC_Kutuphane_2024-12/Views/Duyuru/YeniDuyuru.cshtml
@model Devrekani_Sehitler_Kutuphanesi.Models.Entity.TBL_DUYURULAR

@{
    ViewBag.Title = "YeniDuyuru";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Yeni Duyuru Ekleme Sayfası</h2>
<form class="form-group" method="post">

    <div style="margin-top:15px">
        <label>Duyuru Kategorisi</label>
        @Html.TextBoxFor(y => y.KATEGORI, new { @class = "form-control", @maxlength = "50" })

    </div>
    <div style="margin-top:15px">
        <label>Duyuru İçeriği</label>
        @Html.TextAreaFor(y => y.ICERIK, new { @class = "form-control", @maxlength = "50" })

    </div>
    <div style="margin-top:15px">
        <label>Duyuru Tarihi</label>
        @Html.TextBoxFor(y => y.TARIH, new { @class = "form-control", @maxlength = "50" })

    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="Btn1">Yeni Duyuru Ekle</button>
    </div>
</form>